pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
              checkLatest: true
          
          - script: |
              npm install -g npm@latest
              npm install
              npm run build
            displayName: 'Update npm, Install Dependencies & Build'
          
          - script: |
              npm run test
            displayName: 'Run Tests'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/node-app.zip'
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/node-app.zip
            artifact: node-app


